### ISSUE TITLE
Where does the metadata enter?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/javascript-todo-list-tutorial#19]
While following this tutorial I noticed that "metadata" is mentioned where the metadata enters ? 
I couldn't understand that part because I've never heard of metadata if anyone can help it would be important or maybe it would be better to give an easier explanation to those starting out (I'm not saying it's difficult) but there are some words or technical terms that are hard to understand at first.

**Comment by miguelmartins17** [comment]
I have been able to find more information about metadata and I have been able to understand what it is but I did not understand what the purpose of using metadata in general is, within the project I understood but outside the subject what the purpose is?

https://en.wikipedia.org/wiki/Metadata

**Comment by nelsonic** [comment]
@miguelmartins17 are you referring to the [What about `metadata`?](https://github.com/dwyl/javascript-todo-list-tutorial#what-about-metadata-) section?
![image](https://user-images.githubusercontent.com/194400/73057511-9e918500-3e89-11ea-8eb1-9474e6ff72b7.png)

If you are able to help us _clarify_ what the two types of `metadata` are in this App `id` and `count`, please do.

**Comment by miguelmartins17** [comment]
It says there are two types of metadata in Todo List's wanted to know if there were more features or functions.
I must not have explained myself well.

**Comment by nelsonic** [comment]
Did you _understand_ what metadata _is_?
Did you click the wikipedia link and read it?
What was your _doubt_ after reading the wikipedia article?
The **`metadata`** in a Todo list application is the data that helps the _system_ identify the todo list items or keep track of how many items there are. The _user_ does not have to input this information. The `id` is created by the todo list system and the count is just the total number of times in the list. The _user_ does not need to manually count up their items or input any additional data in order to have a `count`. 

Apologies if _I_ am not understanding where the confusion is ... 😕

**Comment by nelsonic** [comment]
I have opened a Pull Request to _completely_ remove any reference to `metadata` 
to avoid any further confusion to anyone reading this tutorial in the future: #22
Please see: https://github.com/dwyl/javascript-todo-list-tutorial/pull/22/files

**Comment by nelsonic** [comment]
https://github.com/dwyl/javascript-todo-list-tutorial/blob/26845893f7b7e03366438863d767eb1207bd9650/README.md#what-about-the-count-of-items-
