### ISSUE TITLE
Npm-debug.log File

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/javascript-todo-list-tutorial#23]
I'm following the Javascript tutorial but I still have the same error running the npm install command and someone can review this command when they have time.
In the terminal you ask me to add the npm-debug.log file.

![Screen Shot 2020-01-31 at 12 40 26](https://user-images.githubusercontent.com/27420533/73540108-edf62900-4426-11ea-88fe-b4dc06015936.png)

**Comment by nelsonic** [comment]
@miguelmartins17 this screenshot does not tell us very much about how you got to this point.
What `command` did you run to see that error? 
`npm install`? did you run it in an _empty_ directory?
Or in a directory of a repository you _cloned_ from GitHub?
Did you `git clone` _this_ repository? 
e.g: `git clone git@github.com:dwyl/javascript-todo-list-tutorial.git`

What **version** of **`node.js`** are you running? (run `node -v`)

> Consider re-installing `node.js` from https://nodejs.org 

What did **Google** tell you when you _pasted_ the error message and searched for a solution?
```
Failed at the bufferutil@4.0.1 install script 'node-gyp-build'
```
e.g: https://stackoverflow.com/questions/39739626/what-is-node-gyp/39741537
`node-gyp` is a tool which compiles Node.js Addons. Node.js Addons are native Node.js Modules, written in C or C++, which therefore need to be compiled on your machine.

I know that the https://github.com/dwyl/javascript-todo-list-tutorial does not have any Native Addons,
so I'm very surprised to be seeing a `node-gyp` error ... 😕 

Also, when the error message tells you to "_Please include the following file with any support requests_" 
That generally means include the _contents_ of the `npm-debug.log` not a _screenshot_ of the error message ... try running:
``` 
pbcopy < npm-debug.log
```
Then _paste_ the contents of the `npm-debug.log` file in the issue so that someone can help you debug.

**Comment by miguelmartins17** [comment]
@nelsonic I wrote which command I ran, it was the **_npm Install._**
I cloned the **javascript-todo-list-tutorial** repository, I ran the **_npm install_** command inside the repository.

First I cloned the repository.
Then I used the command **_cd javascript-todo-list-tutorial_**.
And then I ran the **_npm install_** command which is where those errors appeared.

At the moment the version I'm using from **node.js** and the version 0.12.1.
This well I'll try now to use the command (pbcopy < npm-debug.log).

**Comment by nelsonic** [comment]
Please update your version of `node.js`. https://nodejs.org ⬆️ 
(_version `0.12.1` is from 2015 ... that was the last time I used the laptop you are working on_) ⏳ 
You should no longer see _any_ `node-gyp` issues once you download the latest version of `node.js`.

**Comment by miguelmartins17** [comment]
@nelsonic Thanks, the mistake really doesn't come up anymore, I'll keep going then. 👍

**Comment by nelsonic** [comment]
Thanks for confirming you are no longer seeing the `node-gyp` error. ✅
