### ISSUE TITLE
The Files already exist

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/javascript-todo-list-tutorial#24]
I am following this tutorial as I get to the step of creating the files when I go to the terminal they already exist.
How or where should I create the three files?

![Screen Shot 2020-02-01 at 12 19 58](https://user-images.githubusercontent.com/27420533/73592051-ea79a500-44ed-11ea-8b5e-b71e42f9aa48.png)

![Screen Shot 2020-02-01 at 12 22 34](https://user-images.githubusercontent.com/27420533/73592058-f7969400-44ed-11ea-8589-5dc51bcb096a.png)

**Comment by miguelmartins17** [comment]
I cloned this repository to my localhost and already installed the dependencies.
This would be the next step but I didn't understand where to create the files. 😕

**Comment by nelsonic** [comment]
@miguelmartins17 the files in the repository are meant as a _reference_.
You are instructed to `git clone` the project to have a local _reference_ or "copy" of it.
You should then create your _own_ version of _all_ the files in your _own_ repository:
https://github.com/miguelmartins17/javascript-todo-list
![image](https://user-images.githubusercontent.com/194400/73592176-5f011380-44ef-11ea-9315-a7ec5dae2852.png)

Think about it this way: 
Nelson has already done the "_homework_" 
(_building a TodoMVC Todo List in `JavaScrip` following TDD_)
He is _giving_ you his homework and _all_ the _instructions_ so that you can _copy_ them.
Now it's up to you to _follow_ the instructions in your _own_ repo so that you _understand_ the result.

**Comment by nelsonic** [comment]
Feel free to create a PR with the step to _create_ a **`NEW`** repository (_which you have already done_)

**Comment by nelsonic** [comment]
Closing as this has been clarified in the `README.md` ✅
