### ISSUE TITLE
Confusing instructions: Create (already present and populated) 3 starting files.

### ISSUE THREAD

**Issue by nemanjaglumac** [dwyl/javascript-todo-list-tutorial#9]
@nelsonic First of all, **HUGE** thank you for all the effort and amazing material you have prepared. I am grateful for the opportunity to learn so many new "things" following your tutorial(s).

With that said, I hope this will not sound like complaining. I am simply confused with the instructions at the very beginning. In the [How](https://github.com/dwyl/todomvc-vanilla-javascript-example#how) section, we are guided to clone the repo and to install dependencies. So far so good.

But then you proceed by saying to **create**  3 new files:

- [test/todo-app.test.js](https://github.com/dwyl/todomvc-vanilla-javascript-example/blob/master/test/todo-app.test.js)
- [lib/todo-app.js](
https://github.com/dwyl/todomvc-vanilla-javascript-example/blob/master/lib/todo-app.js)
- [index.html](
https://github.com/dwyl/todomvc-vanilla-javascript-example/blob/master/index.html)

The thing is - they are already present in the repo with hundreds of lines of code already written in them.

Of course, the easiest thing to do is simply to delete contents of those files and start following (writing from the scratch). Just wanted to check with you if this was intentionally made like this or did I miss something/ did something wrong? Maybe there's some other `starter` repo? This one looks finished.

If I have missed something really obvious, I am sorry in advance.
Many thanks.

N.

**Comment by nelsonic** [comment]
Hi @nemanjaglumac thank you very much for the feedback! 🎉 
On second reading I acknowledge that those instructions are confusing. 😞 
The intention was: 
1. clone this repo so that you have a copy on your `localhost`
2. create a fresh directory where you follow the remaining instructions (_including creating all the files_) from scratch. 

The idea being that by cloning the repository from GitHub you get all the history and can learn/work "offline" ... 🤔 

You haven't missed anything, the instructions need additional clarity. 
The "final" versions of the files you have listed above are indeed in this repository as a _reference_ for the person following the example/tutorial. But the idea is that the person/people following the example/tutorial create each line of the app from scratch for themselves by following the steps.
